import type { Project } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getUrl = (id: string) => PlaceHolderImages.find(p => p.id === id)?.imageUrl || '';

export const projects: Project[] = [
  {
    id: 'proj-1',
    title: 'Alpine Echoes',
    category: 'Landscape',
    description: 'A quiet morning in the Swiss Alps, capturing the first light hitting the peaks. The air was crisp and the silence was only broken by the distant sound of a waterfall.',
    year: 2023,
    client: 'Nature Geographic',
    imageUrl: getUrl('gallery-1'),
    media: [{ type: 'image', url: getUrl('gallery-1') }],
  },
  {
    id: 'proj-2',
    title: 'Neon Dreams',
    category: 'Cityscape',
    description: 'Tokyo\'s vibrant streets after midnight, a symphony of light and movement. This shot aims to capture the energy and solitude of the city at night.',
    year: 2022,
    client: 'Wired Magazine',
    imageUrl: getUrl('gallery-2'),
    media: [{ type: 'image', url: getUrl('gallery-2') }, { type: 'image', url: 'https://picsum.photos/seed/202/800/1200' }],
  },
  {
    id: 'proj-3',
    title: 'The Gaze',
    category: 'Portrait',
    description: 'An intimate portrait capturing raw emotion and vulnerability. The subject\'s eyes tell a story of resilience and hope.',
    year: 2024,
    client: 'Vogue',
    imageUrl: getUrl('gallery-3'),
    media: [{ type: 'image', url: getUrl('gallery-3') }],
  },
  {
    id: 'proj-4',
    title: 'Concrete Jungle',
    category: 'Architecture',
    description: 'Exploring the geometry and scale of modern buildings. A study of lines, shadows, and reflections in an urban environment.',
    year: 2023,
    client: 'ArchDaily',
    imageUrl: getUrl('gallery-4'),
    media: [{ type: 'image', url: getUrl('gallery-4') }],
  },
  {
    id: 'proj-5',
    title: 'Whispering Woods',
    category: 'Nature',
    description: 'A tranquil walk through an ancient forest, with sunbeams piercing through the dense canopy. A moment of pure peace.',
    year: 2022,
    client: 'Self-initiated',
    imageUrl: getUrl('gallery-5'),
    media: [{ type: 'image', url: getUrl('gallery-5') }],
  },
  {
    id: 'proj-6',
    title: 'Azure Tides',
    category: 'Seascape',
    description: 'The powerful and relentless movement of the ocean against volcanic rock. A testament to nature\'s force.',
    year: 2024,
    client: 'Patagonia',
    imageUrl: getUrl('gallery-6'),
    media: [{ type: 'image', url: getUrl('gallery-6') }],
  },
  {
    id: 'proj-7',
    title: 'Big Buck Bunny',
    category: 'Animation Short',
    description: 'A large and lovable rabbit named Big Buck awakens in his rabbit hole, and deals with three pesky rodents: Frank, Rinky, and Gamera.',
    year: 2008,
    client: 'Blender Foundation',
    imageUrl: getUrl('video-card-1'), 
    media: [{ type: 'video', url: getUrl('video-card-1') }],
  },
  {
    id: 'proj-8',
    title: 'Elephants Dream',
    category: 'Animation Short',
    description: 'Emo and Proog, two people with very different visions of the world, explore a strange and surreal machine-like world that reacts to their thoughts and emotions.',
    year: 2006,
    client: 'Blender Foundation',
    imageUrl: getUrl('video-card-2'),
    media: [{ type: 'video', url: getUrl('video-card-2') }],
  },
];
